language: cpp

# Use latest compiler.
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

after_install:
   - export CXX=g++-7
   - export CC=gcc-7

script:
  - echo "Do nothing as of now!"
  - g++-7 --version
