language: cpp

#matrix:
#  include:
    # works on Precise and Trusty
#    - os: linux
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++-6
#      env:
#         - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

script:
  - echo "Do nothing as of now!"
  - gcc-6 --version
